### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by mhsafaeii** [PROaction/pytest-zephyr-scale-integration#1]
After set config and run project in this API (/rest/tests/1.0/testrun) I give "404 Not Found" and just create test cycle. Why ?

**Comment by SerSerPopov** [comment]
Hi, @mhsafaeii

Most likely, this is because the REST API request is not composed correctly. Try the following:
1. Open Zephyr
2. Open DevTool
3. Create a test cycle
4. Find the POST /testrun request in DevTool
5. Copy this request copy --> cBash (curl bash)
6. Paste this request into Postman and send.

If it works correctly, then compare this request with what the library generates.
Perhaps the project key is specified incorrectly. Or the test cycle status is specified incorrectly. Then I will need to fix this.

**Comment by mhsafaeii** [comment]
Hi 
Create testcycle when I run code with your code and set ""statusId": 3247" but in response show 404 not found
Now I follow step by step with your comment. My ""statusId": 32" and give status code "201 created".
This problem is due to wrong set of statusId.

**Comment by mhsafaeii** [comment]
You hardcode set statusId is 3247. Why ?

**Comment by SerSerPopov** [comment]
My mistake. Fixed.
